# Generated by Django 3.2.3 on 2021-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateTimeField()),
                ('vname', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('whom', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'VisitInfo',
            },
        ),
    ]
