# Generated by Django 3.2.3 on 2021-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsApp', '0002_alter_visitinfo_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateTimeField()),
                ('depart', models.CharField(max_length=10)),
                ('organiser', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('attendee', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MeetingInfo',
            },
        ),
    ]
