# Generated by Django 3.2.3 on 2021-06-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsApp', '0004_auto_20210623_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitinfo',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
