# Generated by Django 3.2.3 on 2021-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsApp', '0005_alter_visitinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitinfo',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
