# Generated by Django 3.2.3 on 2021-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsApp', '0009_alter_visitinfo_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitinfo',
            name='mobile',
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='mobile1',
            field=models.CharField(default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='mobile2',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
