# Generated by Django 3.2.3 on 2021-06-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsApp', '0011_auto_20210630_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitinfo',
            name='mobile1',
            field=models.CharField(default='null', max_length=11),
        ),
    ]
